---
title: "Dashboard Soja"
author: "Ítalo Marques-Monteiro"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme:  cerulean
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(plotly)

estados_br <- geobr::read_state(code_state = "all", year = 2020)
soja <- readr::read_csv("C:/Users/italo/Downloads/soja_dashboard.csv")
soja_map <- estados_br |>
  dplyr::left_join(soja)
```

*Ver por estados*
================

Inputs {.sidebar}
---------------
```{r}
shiny::sliderInput("ano", label = "Ano:",
            min = 1977, max = 2023, value = 2023, step = 5)

shiny::selectInput("abbrev_state", label = "Unidade da Federação:",
           choices = unique(soja$abbrev_state), selected = "RS")
```

Row {data-height=350}
---------------------

### **Produtividade**
```{r}
renderPlotly({
  g <- soja |>
    dplyr::filter(abbrev_state == input$abbrev_state,
           ano <= input$ano) |>
    ggplot2::ggplot(aes(x = ano, y = produtividade_kg_ha)) +
        geom_line(color = "#E46726") +
        geom_point(color = "#E46726") +
        scale_x_continuous(breaks = seq(1977, 2023, 5)) +
        theme_bw() +
        labs(x = "Ano", y = "Produtividade (kg-ha)") +
        theme(legend.title = element_text(size = 14),
          legend.text = element_text(size = 12),
          axis.title.x = element_text(size = 12),
          axis.title.y = element_text(size = 12),
          axis.text.y = element_text(size = 10, color = "black"),
          axis.text.x = element_text(size = 10, color = "black",
          angle = 60, hjust = 1, vjust = 1))
    plotly::ggplotly(g)
})
```


### **Área plantada**
```{r}
renderPlotly({
  g <- soja |>
    dplyr::filter(abbrev_state == input$abbrev_state,
           ano <= input$ano) |>
    ggplot(aes(x = ano, y = area_mil_ha)) +
    geom_line(color = "#6D9EC1") +
    geom_point(color = "#6D9EC1") +
    scale_x_continuous(breaks = seq(1977, 2023, 5)) +
    theme_bw() +
    labs(x = "Ano", y = "Área plantada (mil-ha)") +
    theme(legend.title = element_text(size = 14),
      legend.text = element_text(size = 12),
      axis.title.x = element_text(size = 12),
      axis.title.y = element_text(size = 12),
      axis.text.y = element_text(size = 10, color = "black"),
      axis.text.x = element_text(size = 10, color = "black",
      angle = 60, hjust = 1, vjust = 1))
  ggplotly(g)
})
```

Row {.tabset}
-------------

### **Produção**
```{r}
renderPlotly({
  g <- soja |>
    filter(abbrev_state == input$abbrev_state,
           ano <= input$ano) |>
   ggplot2::ggplot(aes(x = ano, y = producao_mil_t)) +
        geom_col(fill = "#0EAD69", color = "black", width = 1) +
        scale_x_continuous(breaks = seq(1977, 2023, 5)) +
        theme_bw() +
        labs(x = "Ano", y = "Procução (mil-t)") +
        labs(fill = "Ano") +
        theme(legend.title = element_text(size = 14),
            legend.text = element_text(size = 12),
            axis.title.x = element_text(size = 12),
            axis.title.y = element_text(size = 12),
            axis.text.y = element_text(size = 10, color = "black"),
            axis.text.x = element_text(size = 10, color = "black",
            angle = 60, hjust = 1, vjust = 1)) +
    scale_x_discrete(limits = c(
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984,
       1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021, 2022, 2023)
       )
    ggplotly(g)
})
```

### **Dados** 
```{r}
renderTable({
  soja |>
    filter(abbrev_state == input$abbrev_state)
})
```

### **Médias Históricas**
```{r}
renderTable({
  soja |>
    dplyr::select(!ano) |>
    filter(abbrev_state == input$abbrev_state) |>
    dplyr::group_by(abbrev_state) |>
    dplyr::summarise(
        across(where(
            is.double), ~mean(
                .x, na.rm = TRUE)))
})
```

*Ver MT vs RS*
======================

Row {data-height=350}
---------------------

### **Série histórica de produtividade por hectare**
```{r}
g <- soja |>
    dplyr::filter(abbrev_state %in% c("RS", "MT")) |>
    ggplot2::ggplot(aes(
            x = as.numeric(ano), y = produtividade_kg_ha)) +
        geom_line(aes(colour = abbrev_state)) +
        theme(
            legend.position = c(0.7, 0.25),
            legend.title = element_text(size = 12),
            legend.text = element_text(size = 10),
            axis.title.x = element_text(size = 12),
            axis.title.y = element_text(size = 12),
            axis.text.y = element_text(size = 10, color = "black"),
            axis.text.x = element_text(
                size = 10, color = "black", angle = 60, hjust = 1, vjust = 1),
            panel.grid.major = element_line(colour = "white"),
            panel.background = element_rect(fill = "gray95"),
            legend.background = element_rect(
            fill = "grey95", colour = "white", size = 1)) +
        labs(
            color = "Estados - BR",
            x = "Safras",
            y = "Produtividade (kg-ha)") +
        scale_y_continuous(breaks = seq(0, 4000, 550)) +
        scale_x_discrete(limits = c(
           1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984,
           1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
           1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
           2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
           2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
           2021, 2022, 2023)
           )
    plotly::ggplotly(g)
```

Row
---
### **Série histórica área por hectare**
```{r}
g <- soja |>
    dplyr::filter(abbrev_state %in% c("RS", "MT")) |>
    ggplot2::ggplot(aes(
            x = as.numeric(ano), y = area_mil_ha)) +
        geom_line(aes(colour = abbrev_state)) +
        theme(
            legend.position = c(0.7, 0.25),
            legend.title = element_text(size = 12),
            legend.text = element_text(size = 10),
            axis.title.x = element_text(size = 12),
            axis.title.y = element_text(size = 12),
            axis.text.y = element_text(size = 10, color = "black"),
            axis.text.x = element_text(
                size = 8, color = "black", angle = 60, hjust = 1, vjust = 1),
            panel.grid.major = element_line(colour = "white"),
            panel.background = element_rect(fill = "gray95"),
            legend.background = element_rect(
            fill = "grey95", colour = "white", size = 1)) +
        labs(
            color = "Estados - BR",
            x = "Safras",
            y = "Área plantada (mil-ha)") +
        scale_y_continuous(breaks = seq(0, 13000, 1500)) +
        scale_x_discrete(limits = c(
           1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984,
           1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
           1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
           2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
           2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
           2021, 2022, 2023)
           )
    plotly::ggplotly(g)
```



### **Série histórica produção por tonelas**
```{r}
g <- soja |>
    dplyr::filter(abbrev_state %in% c("RS", "MT")) |>
    ggplot2::ggplot(aes(
            x = as.numeric(ano), y = producao_mil_t)) +
        geom_line(aes(colour = abbrev_state)) +
        theme(
            legend.position = c(0.7, 0.25),
            legend.title = element_text(size = 12),
            legend.text = element_text(size = 10),
            axis.title.x = element_text(size = 12),
            axis.title.y = element_text(size = 12),
            axis.text.y = element_text(size = 10, color = "black"),
            axis.text.x = element_text(
                size = 8, color = "black", angle = 60, hjust = 1, vjust = 1),
            panel.grid.major = element_line(colour = "white"),
            panel.background = element_rect(fill = "gray95"),
            legend.background = element_rect(
            fill = "grey95", colour = "white", size = 1)) +
        labs(
            color = "Estados - BR",
            x = "Safras",
            y = "Produção (mil-t)") +
        scale_y_continuous(breaks = seq(0, 46000, 5500)) +
        scale_x_discrete(limits = c(
           1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984,
           1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
           1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
           2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
           2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
           2021, 2022, 2023)
           )
    plotly::ggplotly(g)
```